SGE.Web/ViewModels/FiltroPreparacaoVM.cs
using SGE.Dominio.Entidades;
using SGE.Dominio.ObjetoValor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SGE.Web.ViewModels
{
    public class FiltroPreparacaoVM
    {
        public FiltroPreparacaoVM()
        {
            DataInicial = DateTime.Now.ToString("yyyy-MM-dd");
            DataFinal = DateTime.Now.ToString("yyyy-MM-dd"); 
            Situacao = SituacaoPreparacao.Pendente;
            Preparacoes = new List<Preparacao>();
        }
        public String DataInicial { get; set; }
        public String DataFinal { get; set; }
        public SituacaoPreparacao Situacao { get; set; }
        public String Pesquisar { get; set; }
        public IList<Preparacao> Preparacoes { get; set; }
    }
}

SGE.Web/Controllers/HomeController.cs
using SGE.Repositorio.Configuracao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGE.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Entrar", "Login");
            else
                return View();

        }


    }
}

SGE.Web/Controllers/LoginController.cs
using Doctus.Utils.Text;

using SGE.Dominio.Entidades;
using SGE.Repositorio.Repositorios;
using SGE.Web.Utilitarios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace SGE.Web.Controllers
{
    public class LoginController : Controller
    {
       
        #region Repositorio
        private RepositorioUsuario _repositorio;
        public RepositorioUsuario Repositorio
        {
            get
            {
                if (_repositorio == null)
                    _repositorio = new RepositorioUsuario(NHibernateHttpModule.CurrentSession);

                return _repositorio;
            }
            set { _repositorio = value; }
        }
        #endregion
        public ActionResult Entrar()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Entrar(string txtUser, string txtSenha)
        {
            if (!String.IsNullOrEmpty(txtUser) && !String.IsNullOrEmpty(txtSenha))
            {
                var usuario = Repositorio.ObterPorParametros(x => x.Login == txtUser).FirstOrDefault();

                if (usuario != null)
                {

                    if (usuario.Senha == Criptografia.GerarHashSHA1(txtSenha))
                    {
                        AutenticarUsuario(usuario);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                        TempData["Mensagem"] = "Senha Inválida!";
                }
                else
                    TempData["Mensagem"] = "Usuario não encontrado!";
            }
            else
                TempData["Mensagem"] = "Usuario ou Senha invalidos!";

            return View();
        }

        private void AutenticarUsuario(Usuario usuario)
        {
            FormsAuthenticationTicket authenticationTicket = new FormsAuthenticationTicket(
                                                    1,
                                                    usuario.Id.ToString(),
                                                    DateTime.Now,
                                                    DateTime.Now.AddHours(12), //.Add(FormsAuthentication.Timeout)
                                                    false,
                                                    usuario.TipoUsuario.ConverteEnumParaString());

            String encryptTicket = FormsAuthentication.Encrypt(authenticationTicket);
            HttpCookie authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptTicket);
            authCookie.Expires = authenticationTicket.Expiration;

            Response.Cookies.Add(authCookie);
            Configuracao.Usuario = usuario;
        }
    }
}

SGE.Web/Controllers/MenuController.cs
using SGE.Web.Utilitarios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGE.Web.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult Menus()
        {
            var menus = Configuracao.Menus;
            return PartialView(menus);
        }
    }
}

SGE.Web/Controllers/PreparacaoController.cs
using LinqKit;
using SGE.Dominio.Entidades;
using SGE.Repositorio.Repositorios;
using SGE.Web.Utilitarios;
using SGE.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGE.Web.Controllers
{
    public class PreparacaoController : Controller
    {
        #region Repositorio
        private RepositorioPreparacao _repositorio;
        public RepositorioPreparacao Repositorio
        {
            get
            {
                if (_repositorio == null)
                    _repositorio = new RepositorioPreparacao(NHibernateHttpModule.CurrentSession);
                return _repositorio;
            }
            set { _repositorio = value; }
        }
        #endregion

        Preparacao preparacao = new Preparacao();

        // GET: Preparacao
        public ActionResult Index(FiltroPreparacaoVM filtros)
        {
            if (filtros == null)
                filtros = new FiltroPreparacaoVM();
            var predicado = PredicateBuilder.True<Preparacao>();

            predicado = predicado.And(x => x.DataGeracao >= Convert.ToDateTime(filtros.DataInicial));
            predicado = predicado.And(x => x.DataGeracao <= Convert.ToDateTime(filtros.DataFinal).AddHours(23).AddMinutes(59).AddSeconds(59));
            predicado = predicado.And(x => x.SituacaoPreparacao == filtros.Situacao);
            if (!String.IsNullOrEmpty(filtros.Pesquisar))
            {
                string pesquisar = filtros.Pesquisar.ToLower();
                predicado = predicado.And(x => (x.Cliente.Nome.ToLower().Contains(pesquisar) || x.Cliente.Id.ToString().Contains(pesquisar) || x.Id.ToString().Contains(pesquisar)));

            }
            var preparacoes = Repositorio.ObterPorParametros(predicado).ToList();
            filtros.Preparacoes = preparacoes;


            return View(filtros);
        }
    }
}

SGE.Web/Controllers/SetorController.cs
using SGE.Dominio.Entidades;
using SGE.Repositorio.Repositorios;
using SGE.Web.Utilitarios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGE.Web.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class SetorController : Controller
    {
        #region Repositorio
        private RepositorioSetor _repositorio;
        public RepositorioSetor Repositorio
        {
            get
            {
                if (_repositorio == null)
                    _repositorio = new RepositorioSetor(NHibernateHttpModule.CurrentSession);

                return _repositorio;
            }
            set { _repositorio = value; }
        }
        #endregion

        Setor setor = new Setor();

        // GET: Setor
        public ActionResult Index()
        {
            var setores = Repositorio.ObterTodos().ToList();
            return View(setores);
        }

        public ActionResult Editar(Int64 id = 0)
        {
            if(id > 0)
            {
                setor = Repositorio.ObterPorId(id);
            }
            return View(setor);
        }

        [HttpPost]
        public ActionResult Editar(Setor setorVM)
        {
            if (String.IsNullOrEmpty(setorVM.Nome))
                ModelState.AddModelError("Nome", "Nome obrigatorio!");
            if (ModelState.IsValid)
            {
                if (setorVM.Id > 0)
                {
                    setor = Repositorio.ObterPorId(setorVM.Id);
                }
                setor.Nome = setorVM.Nome;
                setor.Situacao = setorVM.Situacao;
                if (setorVM.Id == 0)
                    Repositorio.Salvar(setor);
                else
                    Repositorio.Alterar(setor);
                return RedirectToAction("Index");
            }
            
            return View(setor);
        }

        public ActionResult Excluir(Int64 id)
        {
            if(id > 0)
            {
                setor = Repositorio.ObterPorId(id);
                Repositorio.Excluir(setor);
            }
            return RedirectToAction("Index");
        }

    }
}

SGE.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SGE.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SGE.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Principal";
}

SGE.Web/Views/Login/Entrar.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Entrar</title>
    <link href="~/Content/Sign.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div id="login">
            <h2>Login</h2>
            @using (Html.BeginForm("Entrar", "Login", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="item">
                    @Html.TextBox("txtUser","", new { @class = "form-control", @placeholder = "Usuário" })

                </div>
                <div class="item">
                    @Html.Password("txtSenha","", new { @class = "form-control", @placeholder = "Senha" })
                </div>

                <div class="item">
                    <button type="submit">Entrar</button>
                </div>

                <div class="item">
                    @TempData["Mensagem"]
                </div>
            }

        </div>
    </div>
</body>
</html>

SGE.Web/Views/Menu/Menus.cshtml
@model IList<SGE.Dominio.Entidades.Menu>

<ul class="navbar-nav mr-auto">
   
    @foreach (var item in Model.Where(x => x.MenuPai == null))
    {
        if (item.Items.Count == 0)
        {
            <li class="nav-item">
                <a class="nav-link" href="@item.Link">@item.Nome</a>
            </li>
        }
        else if (item.Items.Count > 0)
        {
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @item.Nome
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    @foreach (var item2 in item.Items)
                    {
                        <a class="dropdown-item" href="@item2.Link">@item2.Nome</a>
                    }

                </div>
            </li>
        }

    }
</ul>

SGE.Web/Views/Preparacao/Index.cshtml
@model SGE.Web.ViewModels.FiltroPreparacaoVM

@{
    ViewBag.Title = "Preparações";
}

<div class="row mb-3 mt-3">
    <div class="col-6">
        <h2>Consulta Preparações</h2>
    </div>
    <div class="col-6 text-right">
        @Html.ActionLink("Novo", "Editar", new { id = 0 }, new { @class = "btn corBotao" })
    </div>
</div>

@using (Html.BeginForm("Index", "Preparacao", FormMethod.Get, new { @class = "form-horizontal mb-3" }))
{
    <div class="row">
        <div class="col-md-3">
            @Html.LabelFor(x => x.DataInicial, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(x => x.DataInicial, new { htmlAttributes = new { @class = "form-control", @type = "date" } })

        </div>
        <div class="col-md-3">
            @Html.LabelFor(x => x.DataFinal, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(x => x.DataFinal, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(x => x.Situacao, htmlAttributes: new { @class = "control-label" })
            @Html.EnumDropDownListFor(x => x.Situacao, new { @class = "form-control" })
        </div>
        <div class="col-md-3">
            @Html.LabelFor(x => x.Pesquisar, htmlAttributes: new { @class = "control-label" })
            @Html.TextBoxFor(x => x.Pesquisar, new { @class = "form-control" })
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12">
            <button type="submit" class="btn corBotao"> Pesquisa Avançada</button>
        </div>

    </div>
}


<div class="col-12">
    <table id="Tabela" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Situacao</th>
                <th>Compra</th>
                <th>Cliente</th>
                <th>Valor</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Preparacoes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => item.SituacaoPreparacao)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Cliente.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Total)
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Editar", "Editar", new { id = item.Id }, new { @class = "btn corBotao" })
                        <a class="btn btn-warning" href="@Url.Action("Excluir", "Preparacao", new { id = item.Id})" onclick="return confirm('Deseja realmente excluir?')">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(function () {
        $("#Tabela").DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
            }
        });
    });
</script>

SGE.Web/Views/Setor/Editar.cshtml
@model SGE.Dominio.Entidades.Setor

@{
    ViewBag.Title = Model.Id > 0 ? "Editar Setor" : "Novo Setor";
}

<div class="row">
    <div class="col-12">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Editar", "Setor", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.HiddenFor(x =>x.Id)
            <div class="form-group">
                @Html.LabelFor(x => x.Nome, htmlAttributes: new { @class="control-label"})
                <div class="col-md-12">
                    @Html.TextBoxFor(x => x.Nome, new { @class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Nome)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Situacao, htmlAttributes: new { @class="control-label"})
                <div class="col-md-12">
                    @Html.EnumDropDownListFor(x => x.Situacao, new { @class=" form-control"})
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <button class="btn corBotao " type="submit">Salvar</button>
                    <a class="btn corBotao" href="@Url.Action("Index")">Voltar</a>
                </div>
            </div>
        }
    </div>

</div>

SGE.Web/Views/Setor/Index.cshtml
@model IList<SGE.Dominio.Entidades.Setor>

@{
    ViewBag.Title = "Setores";
}

<div class="row mb-3 mt-3">
    <div class="col-6">
        <h2> Consulta Setores</h2>
    </div>
    <div class="col-6 text-right">
        @Html.ActionLink("Novo", "Editar", new { id = 0 }, new { @class = "btn corBotao" })
    </div>
</div>


<div class="col-12">
    <table id="Tabela" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Situação</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => item.Nome)
                        
                    </td>
                    <td>
                        @Html.DisplayFor(x => item.Situacao)
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Editar", "Editar", new { id = item.Id }, new { @class = "btn corBotao" })
                        <a class="btn corBotao" href="@Url.Action("Excluir", "Setor", new { id = item.Id})" onclick="return confirm('Deseja realmente excluir?')"> Excluir</a>
                       
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $("#Tabela").DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
            },
            "pageLength": 50
        });
    });
</script>

SGE.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">Empresa</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            @{ Html.RenderAction("Menus", "Menu");}
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
</body>
</html>